version: "3.7"
services:
  server:
    container_name: seguranca_server
    build: .
    ports:
      - 8081:8080
      - 8787:8787
      - 4000:4000
    env_file:
      - docker-compose.env
    environment:
      JAVA_OPTS: -Xms256m -Xmx512m